"""
AXIOM Phase 1-5 API Endpoints
New routes: LBO, football field, sensitivity, exports, live stream, data layer, alerts.
Register with: register_axiom_routes(app)
"""

import json
import logging
import time
import io
from datetime import datetime
from flask import jsonify, request, Response, send_file

logger = logging.getLogger(__name__)

# ---- Share Link HTML Templates -----------------------------------------------

SHARE_NOT_FOUND_HTML = '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>AXIOM — Link Unavailable</title>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;\n           background: #0d1117; color: #e6edf3; display: flex; justify-content: center;\n           align-items: center; height: 100vh; margin: 0; }\n    .box { text-align: center; max-width: 400px; }\n    h1 { font-size: 1.5rem; margin-bottom: 0.5rem; }\n    p { color: #8b949e; }\n    a { color: #58a6ff; text-decoration: none; }\n  </style>\n</head>\n<body>\n  <div class="box">\n    <h1>AXIOM</h1>\n    <p>{{ reason }}</p>\n    <p><a href="/">Go to Dashboard</a></p>\n  </div>\n</body>\n</html>'

SHARE_VIEW_HTML = '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <title>AXIOM Shared View — {{ snapshot.name }}</title>\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;\n           background: #0d1117; color: #e6edf3; margin: 0; padding: 2rem; }\n    .banner { background: #161b22; border: 1px solid #30363d; border-radius: 6px;\n              padding: 0.6rem 1rem; margin-bottom: 2rem; font-size: 0.85rem; color: #8b949e;\n              display: flex; justify-content: space-between; align-items: center; }\n    .banner strong { color: #f0883e; }\n    h1 { font-size: 1.8rem; margin: 0 0 0.25rem; }\n    .ticker { color: #58a6ff; font-size: 1.1rem; margin-bottom: 2rem; }\n    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 2rem 0; }\n    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.25rem; }\n    .card-label { font-size: 0.75rem; color: #8b949e; text-transform: uppercase; letter-spacing: 0.05em; }\n    .card-value { font-size: 1.5rem; font-weight: 700; margin-top: 0.25rem; font-family: "Courier New", monospace; }\n    .buy { color: #3fb950; } .hold { color: #d29922; } .sell { color: #f85149; }\n    .footer { margin-top: 3rem; font-size: 0.8rem; color: #8b949e; border-top: 1px solid #30363d; padding-top: 1rem; }\n  </style>\n</head>\n<body>\n  <div class="banner">\n    <span><strong>AXIOM</strong> Shared Valuation View &nbsp; Read Only</span>\n    <span>Data as of {{ created_at }} &nbsp; {{ view_count }} view{{ "s" if view_count != 1 else "" }}</span>\n  </div>\n  <h1>{{ snapshot.name }}</h1>\n  <div class="ticker">{{ snapshot.get("ticker", "") }} &nbsp; {{ snapshot.get("sector", "") }}</div>\n  <div class="grid">\n    <div class="card">\n      <div class="card-label">Fair Value (DCF)</div>\n      <div class="card-value">${{ "{:,.2f}".format(snapshot.get("final_price_per_share") or 0) }}</div>\n    </div>\n    <div class="card">\n      <div class="card-label">Current Price</div>\n      <div class="card-value">${{ "{:,.2f}".format(snapshot.get("current_price") or 0) }}</div>\n    </div>\n    <div class="card">\n      <div class="card-label">Upside / Downside</div>\n      <div class="card-value {{ "buy" if (snapshot.get("upside_pct") or 0) > 5 else "sell" if (snapshot.get("upside_pct") or 0) < -5 else "hold" }}">\n        {{ "{:+.1f}".format(snapshot.get("upside_pct") or 0) }}%\n      </div>\n    </div>\n    <div class="card">\n      <div class="card-label">Recommendation</div>\n      <div class="card-value {{ "buy" if "BUY" in (snapshot.get("recommendation") or "") else "sell" if "SELL" in (snapshot.get("recommendation") or "") else "hold" }}">\n        {{ snapshot.get("recommendation") or "N/A" }}\n      </div>\n    </div>\n    {% if snapshot.get("wacc") %}\n    <div class="card">\n      <div class="card-label">WACC</div>\n      <div class="card-value">{{ "{:.1f}".format((snapshot.get("wacc") or 0) * 100) }}%</div>\n    </div>\n    {% endif %}\n  </div>\n  <div class="footer">\n    Read-only snapshot generated by AXIOM on {{ created_at }}.\n    Audit trail and internal notes are not shown in shared views.\n    This analysis does not constitute investment advice.\n  </div>\n</body>\n</html>'



def _get_db():
    """
    Get database connection respecting Config.DATABASE_TYPE.
    Supports both PostgreSQL and SQLite.
    """
    from config import Config
    if Config.DATABASE_TYPE == 'postgresql':
        import psycopg2
        from psycopg2.extras import RealDictCursor
        return psycopg2.connect(
            Config.get_db_connection_string(),
            cursor_factory=RealDictCursor
        ), '%s'
    else:
        import sqlite3
        conn = sqlite3.connect(Config.SQLITE_DB)
        conn.row_factory = sqlite3.Row
        return conn, '?'


def _row_to_dict(row):
    """Convert DB row to plain dict (works for both psycopg2 and sqlite3)."""
    if row is None:
        return None
    if isinstance(row, dict):
        return row
    return dict(row)



# ── Institutional Score Utility ────────────────────────────────────────────────

def compute_institutional_score(company_data: dict) -> dict:
    """
    Compute an institutional quality/complexity score for a company.
    Wraps InstitutionalValuationEngine using available company_data fields.
    Returns a dict with: quality_score (0-1), complexity, confidence, wacc_suggestion.
    """
    try:
        from institutional_valuation_engine import InstitutionalValuationEngine, CompanyProfile

        revenue = float(company_data.get('revenue') or 0)
        ebitda = float(company_data.get('ebitda') or 0)
        market_cap = float(company_data.get('market_cap_estimate') or 0)
        debt = float(company_data.get('debt') or 0)
        cash = float(company_data.get('cash') or 0)
        beta = float(company_data.get('beta') or 1.0)
        growth_1y = float(company_data.get('growth_rate_y1') or 0.05)
        terminal_g = float(company_data.get('terminal_growth') or 0.025)
        profit_margin = float(company_data.get('profit_margin') or 0.10)
        capex_pct = float(company_data.get('capex_pct') or 0.05)

        ebitda_margin = (ebitda / revenue) if revenue > 0 else 0.15
        net_ev = market_cap + debt - cash
        leverage = (debt - cash) / ebitda if ebitda > 0 else 1.0

        profile = CompanyProfile(
            name=company_data.get('name', 'Unknown'),
            sector=company_data.get('sector', 'Technology'),
            revenue=revenue,
            market_cap=market_cap,
            enterprise_value=net_ev,
            ebitda_margin=ebitda_margin,
            operating_margin=ebitda_margin * 0.85,
            net_margin=profit_margin,
            roe=0.15,
            roic=0.12,
            revenue_growth_3y_cagr=growth_1y,
            revenue_growth_1y=growth_1y,
            expected_growth_3y=growth_1y * 0.85,
            fcf_conversion=0.85,
            cash_conversion_cycle=45,
            asset_turnover=0.8,
            leverage_ratio=max(0, leverage),
            interest_coverage=max(1, ebitda / max(1, debt * 0.05)),
            volatility=beta,
            capex_to_revenue=capex_pct,
            capex_to_depreciation=1.2,
            working_capital_intensity=0.05,
        )

        engine = InstitutionalValuationEngine()
        quality_score = engine._calculate_quality_score(profile)
        complexity = engine.determine_valuation_complexity(profile)
        confidence = engine._calculate_confidence(quality_score, 5)

        wacc_dict = engine.derive_discount_rate(profile, [])
        growth_dict = engine.derive_growth_assumptions(profile, [])

        return {
            'quality_score': round(quality_score, 3),
            'quality_grade': 'A' if quality_score > 0.75 else 'B' if quality_score > 0.55 else 'C' if quality_score > 0.35 else 'D',
            'complexity': complexity.value,
            'confidence': confidence,
            'suggested_wacc': round(wacc_dict.get('wacc', 0.09), 4),
            'suggested_terminal_growth': round(growth_dict.get('terminal_growth', 0.025), 4),
            'wacc_rationale': wacc_dict.get('rationale', ''),
        }
    except Exception as e:
        logger.warning(f'Institutional score failed: {e}')
        return {
            'quality_score': None,
            'error': str(e),
        }


def register_axiom_routes(app):
    """Register all AXIOM Phase 1-5 routes on the Flask app."""

    # ── Macro / FRED Rates ────────────────────────────────────────────────────

    @app.route('/api/macro/rates', methods=['GET'])
    def get_macro_rates():
        """Return live macro rates from FRED (with 4h cache). Graceful fallback."""
        try:
            from data_layer import DataLayer
            dl = DataLayer()
            rates_raw = dl.get_macro_rates()
            rates = {}
            for key, result in rates_raw.items():
                rates[key] = {
                    'value': result.value,
                    'source': result.source,
                    'available': result.available,
                    'gap_reason': result.gap_reason,
                }
            return jsonify({'rates': rates, 'fetched_at': datetime.utcnow().isoformat()})
        except Exception as e:
            logger.error(f'Error fetching macro rates: {e}')
            return jsonify({'error': str(e), 'rates': {}}), 500

    # ── Company Financials (EDGAR) ────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/financials', methods=['GET'])
    def get_company_edgar_financials(company_id):
        """Fetch company financials from SEC EDGAR XBRL with source attribution."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f'SELECT name, sector FROM companies WHERE id = {ph}', (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            ticker = request.args.get('ticker', row['name'].split()[0].upper())

            from data_layer import DataLayer
            dl = DataLayer()
            result = dl.get_company_financials(ticker)

            return jsonify({
                'company_id': company_id,
                'ticker': ticker,
                'data': result.value,
                'source': result.source,
                'available': result.available,
                'gap_reason': result.gap_reason,
                'fetched_at': result.fetched_at.isoformat(),
            })
        except Exception as e:
            logger.error(f'EDGAR financials failed for company {company_id}: {e}')
            return jsonify({'error': str(e)}), 500

    # ── LBO Analysis ──────────────────────────────────────────────────────────

    @app.route('/api/lbo/<int:company_id>', methods=['POST'])
    def run_lbo_analysis(company_id):
        """
        Run PE-style LBO model.
        Body: {"entry_multiple": 10, "leverage": 5, "hold_period": 5, "exit_multiple": 10}
        """
        try:
            data = request.json or {}
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, cf.ebitda, cf.revenue, cf.capex_pct, cf.tax_rate
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                WHERE c.id = {ph}
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            entry_ebitda = float(row['ebitda'] or 0)
            if entry_ebitda <= 0:
                return jsonify({'error': 'EBITDA must be positive for LBO analysis'}), 400

            revenue = float(row['revenue'] or 1)
            ebitda_margin_entry = entry_ebitda / revenue if revenue > 0 else 0.20

            from lbo_engine import LBOInputs, run_lbo
            entry_mult = float(data.get('entry_multiple', 10.0))
            inputs = LBOInputs(
                entry_ev_ebitda=entry_mult,
                entry_ebitda=entry_ebitda,
                debt_to_ebitda=float(data.get('leverage', 5.0)),
                interest_rate=float(data.get('interest_rate', 0.075)),
                revenue_growth=data.get('revenue_growth', [0.08, 0.07, 0.06, 0.05, 0.05]),
                ebitda_margin_entry=ebitda_margin_entry,
                ebitda_margin_exit=float(data.get('ebitda_margin_exit', ebitda_margin_entry * 1.1)),
                exit_ev_ebitda=float(data.get('exit_multiple', entry_mult)),
                hold_period=int(data.get('hold_period', 5)),
                tax_rate=float(row['tax_rate'] or 0.25),
                capex_pct_revenue=float(row['capex_pct'] or 0.03),
            )
            result = run_lbo(inputs)
            return jsonify(result.to_dict())

        except ValueError as e:
            return jsonify({'error': str(e)}), 400
        except Exception as e:
            logger.error(f'LBO failed for company {company_id}: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── Football Field ────────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/football-field', methods=['GET'])
    def get_football_field(company_id):
        """Return football field valuation ranges with source attribution."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.sector, cf.revenue, cf.ebitda, cf.shares_outstanding,
                       vr.dcf_price_per_share, vr.final_price_per_share,
                       vr.current_price, vr.wacc
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                WHERE c.id = {ph}
                ORDER BY vr.id DESC
                LIMIT 1
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            current_price = float(row.get('current_price') or 0)
            dcf_value = float(row.get('dcf_price_per_share') or 0)

            from football_field import build_football_field
            valuation_results = {
                'dcf_value': dcf_value,
                'fair_value': dcf_value,
                'bear_value': dcf_value * 0.80 if dcf_value else None,
                'bull_value': dcf_value * 1.20 if dcf_value else None,
                'current_price': current_price,
            }
            row['current_price'] = current_price
            result = build_football_field(row, valuation_results)
            return jsonify(result)

        except Exception as e:
            logger.error(f'Football field failed for company {company_id}: {e}')
            return jsonify({'error': str(e)}), 500

    # ── Sensitivity Table ─────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/sensitivity', methods=['GET'])
    def get_sensitivity_table(company_id):
        """2D DCF sensitivity table. Query: ?x=wacc&y=terminal_growth"""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT cf.revenue, cf.ebitda, cf.growth_rate_y1, cf.growth_rate_y2,
                       cf.growth_rate_y3, cf.terminal_growth, cf.capex_pct,
                       cf.tax_rate, cf.shares_outstanding, cf.debt, cf.cash,
                       vr.wacc, vr.current_price
                FROM company_financials cf
                LEFT JOIN valuation_results vr ON cf.company_id = vr.company_id
                WHERE cf.company_id = {ph}
                ORDER BY vr.id DESC
                LIMIT 1
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            revenue = float(row['revenue'] or 0)
            ebitda = float(row['ebitda'] or 0)
            wacc = float(row['wacc'] or 0.09)
            terminal_growth = float(row['terminal_growth'] or 0.025)
            capex_pct = float(row['capex_pct'] or 0.05)
            tax_rate = float(row['tax_rate'] or 0.21)
            shares = float(row['shares_outstanding'] or 1)
            net_debt = float(row['debt'] or 0) - float(row['cash'] or 0)
            current_price = float(row['current_price'] or 0)

            growth_rates = [
                float(row['growth_rate_y1'] or 0.08),
                float(row['growth_rate_y2'] or 0.06),
                float(row['growth_rate_y3'] or 0.05),
            ]
            for _ in range(7):
                g = max(terminal_growth, growth_rates[-1] * 0.9)
                growth_rates.append(g)

            ebitda_margin = ebitda / revenue if revenue > 0 else 0.20
            fcfs, rev = [], revenue
            for g in growth_rates:
                rev = rev * (1 + g)
                nopat = rev * ebitda_margin * (1 - tax_rate)
                fcfs.append(nopat - (rev * capex_pct))

            base_inputs = {
                'projected_fcfs': fcfs,
                'shares_outstanding': shares,
                'net_debt': net_debt,
                'wacc': wacc,
                'terminal_growth': terminal_growth,
            }

            from sensitivity import compute_sensitivity_table
            result = compute_sensitivity_table(
                base_inputs, current_price,
                request.args.get('x', 'wacc'),
                request.args.get('y', 'terminal_growth'),
            )
            return jsonify(result)

        except Exception as e:
            logger.error(f'Sensitivity table failed for company {company_id}: {e}')
            return jsonify({'error': str(e)}), 500

    # ── Peer Discovery ────────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/peers', methods=['GET'])
    def get_company_peers(company_id):
        """Find peer companies via SEC EDGAR SIC code matching."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f'SELECT name, sector FROM companies WHERE id = {ph}', (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            ticker = request.args.get('ticker', row['name'].split()[0].upper())
            market_cap = request.args.get('market_cap', type=float)

            from peer_discovery import find_peers
            result = find_peers(ticker, market_cap=market_cap)
            return jsonify(result)

        except Exception as e:
            logger.error(f'Peer discovery failed for company {company_id}: {e}')
            return jsonify({'error': str(e)}), 500

    # ── Anomaly Detection ─────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/anomalies', methods=['GET'])
    def get_assumption_anomalies(company_id):
        """Check assumptions for statistical outliers vs sector median."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.sector,
                       cf.revenue, cf.ebitda,
                       cf.growth_rate_y1, cf.terminal_growth, cf.beta,
                       vr.wacc
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                WHERE c.id = {ph}
                ORDER BY vr.id DESC
                LIMIT 1
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            assumptions = {
                'wacc': row.get('wacc'),
                'terminal_growth': row.get('terminal_growth'),
                'revenue': row.get('revenue'),
                'ebitda': row.get('ebitda'),
                'growth_rate_y1': row.get('growth_rate_y1'),
                'beta': row.get('beta'),
            }

            from intelligence.anomaly_detector import analyze_assumptions, get_anomaly_summary
            anomalies = analyze_assumptions(assumptions, row.get('sector', 'default'))
            return jsonify(get_anomaly_summary(anomalies))

        except Exception as e:
            logger.error(f'Anomaly detection failed for company {company_id}: {e}')
            return jsonify({'error': str(e)}), 500

    # ── Alerts ────────────────────────────────────────────────────────────────

    @app.route('/api/alerts', methods=['GET'])
    def get_alerts():
        """Get unread alerts for sidebar badge + notification panel."""
        try:
            from intelligence.alert_engine import get_unread_alerts, get_alert_count
            alerts = get_unread_alerts(limit=int(request.args.get('limit', 50)))
            count = get_alert_count()
            return jsonify({'count': count, 'alerts': alerts})
        except Exception as e:
            return jsonify({'count': 0, 'alerts': [], 'error': str(e)})

    @app.route('/api/alerts/<int:alert_id>/read', methods=['POST'])
    def mark_alert_read(alert_id):
        """Mark a specific alert as read."""
        try:
            from intelligence.alert_engine import mark_read
            mark_read(alert_id)
            return jsonify({'success': True})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    @app.route('/api/alerts/read-all', methods=['POST'])
    def mark_all_alerts_read():
        """Mark all alerts as read."""
        try:
            from intelligence.alert_engine import mark_all_read
            mark_all_read()
            return jsonify({'success': True})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    # ── Excel Export ──────────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/export/excel', methods=['GET'])
    def export_excel(company_id):
        """Generate and download Excel DCF model (.xlsx)."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.sector,
                       cf.revenue, cf.ebitda, cf.growth_rate_y1, cf.growth_rate_y2,
                       cf.growth_rate_y3, cf.terminal_growth, cf.tax_rate,
                       cf.shares_outstanding, cf.beta, cf.risk_free_rate,
                       cf.market_risk_premium, cf.capex_pct, cf.debt, cf.cash,
                       vr.dcf_price_per_share, vr.final_price_per_share,
                       vr.wacc, vr.current_price, vr.upside_pct
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                WHERE c.id = {ph}
                ORDER BY vr.id DESC
                LIMIT 1
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            company = {
                'name': row['name'],
                'ticker': row['name'].split()[0].upper(),
                'sector': row['sector'],
                'current_price': row.get('current_price'),
                'revenue': row['revenue'],
                'ebitda': row['ebitda'],
            }
            valuation = {
                'fair_value': row.get('dcf_price_per_share') or row.get('final_price_per_share'),
                'dcf_value': row.get('dcf_price_per_share'),
                'wacc': row.get('wacc', 0.09),
                'terminal_growth': row.get('terminal_growth', 0.025),
                'beta': row.get('beta', 1.0),
                'risk_free_rate': row.get('risk_free_rate', 0.044),
                'market_risk_premium': row.get('market_risk_premium', 0.065),
                'tax_rate': row.get('tax_rate', 0.21),
                'capex_pct': row.get('capex_pct', 0.05),
                'shares_outstanding': row.get('shares_outstanding'),
                'net_debt': (row.get('debt') or 0) - (row.get('cash') or 0),
                'growth_rate_y1': row.get('growth_rate_y1'),
                'growth_rate_y2': row.get('growth_rate_y2'),
                'growth_rate_y3': row.get('growth_rate_y3'),
                'upside_pct': row.get('upside_pct'),
                'current_price': row.get('current_price'),
            }

            from exports.excel_generator import generate_excel
            excel_bytes = generate_excel(company, valuation)

            ticker = company['ticker']
            filename = f'AXIOM_{ticker}_DCF_{datetime.utcnow().strftime("%Y%m%d")}.xlsx'
            return send_file(
                io.BytesIO(excel_bytes),
                mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                as_attachment=True,
                download_name=filename,
            )

        except ImportError:
            return jsonify({'error': 'openpyxl required: pip install openpyxl'}), 503
        except Exception as e:
            logger.error(f'Excel export failed for company {company_id}: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── PDF Export ────────────────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/export/pdf', methods=['GET'])
    def export_pdf(company_id):
        """Generate and download executive PDF pitchbook."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.sector,
                       cf.revenue, cf.ebitda, cf.terminal_growth, cf.beta,
                       cf.risk_free_rate, cf.market_risk_premium, cf.shares_outstanding,
                       cf.debt, cf.cash, cf.tax_rate, cf.capex_pct,
                       cf.growth_rate_y1, cf.growth_rate_y2, cf.growth_rate_y3,
                       vr.dcf_price_per_share, vr.final_price_per_share,
                       vr.wacc, vr.current_price, vr.upside_pct
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                WHERE c.id = {ph}
                ORDER BY vr.id DESC
                LIMIT 1
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()

            if not row:
                return jsonify({'error': f'Company {company_id} not found'}), 404

            company = {
                'name': row['name'],
                'ticker': row['name'].split()[0].upper(),
                'sector': row['sector'],
                'current_price': row.get('current_price'),
                'revenue': row['revenue'],
                'ebitda': row['ebitda'],
            }
            valuation = {
                'fair_value': row.get('dcf_price_per_share') or row.get('final_price_per_share'),
                'dcf_value': row.get('dcf_price_per_share'),
                'wacc': row.get('wacc', 0.09),
                'terminal_growth': row.get('terminal_growth', 0.025),
                'beta': row.get('beta', 1.0),
                'risk_free_rate': row.get('risk_free_rate', 0.044),
                'market_risk_premium': row.get('market_risk_premium', 0.065),
                'upside_pct': row.get('upside_pct'),
            }

            from exports.pdf_generator import generate_pdf
            pdf_bytes = generate_pdf(company, valuation)

            ticker = company['ticker']
            filename = f'AXIOM_{ticker}_Pitchbook_{datetime.utcnow().strftime("%Y%m%d")}.pdf'
            return send_file(
                io.BytesIO(pdf_bytes),
                mimetype='application/pdf',
                as_attachment=True,
                download_name=filename,
            )

        except ImportError as e:
            return jsonify({
                'error': 'WeasyPrint not available. Install: pip install weasyprint && brew install pango',
                'detail': str(e),
            }), 503
        except Exception as e:
            logger.error(f'PDF export failed for company {company_id}: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── Server-Sent Events Live Stream ────────────────────────────────────────

    @app.route('/api/live/stream', methods=['GET'])
    def live_stream():
        """
        SSE stream for live data panel. Sends every 30s.
        Reads from cache only — no new API calls per connected client.
        """
        def generate():
            while True:
                try:
                    payload = {}

                    try:
                        from data_layer import DataLayer
                        dl = DataLayer()
                        rates_raw = dl.get_macro_rates()
                        payload['rates'] = {
                            k: {'value': v.value, 'source': v.source}
                            for k, v in rates_raw.items() if v.available
                        }
                    except Exception:
                        payload['rates'] = {}

                    try:
                        from intelligence.alert_engine import get_alert_count
                        payload['alert_count'] = get_alert_count()
                    except Exception:
                        payload['alert_count'] = 0

                    payload['timestamp'] = datetime.utcnow().isoformat()
                    yield f"data: {json.dumps(payload)}\n\n"

                except GeneratorExit:
                    break
                except Exception as e:
                    yield f"data: {json.dumps({'error': str(e)})}\n\n"

                time.sleep(30)

        return Response(
            generate(),
            mimetype='text/event-stream',
            headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'},
        )


    # ── Institutional Score ───────────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/institutional-score', methods=['GET'])
    def get_institutional_score(company_id):
        """
        Run InstitutionalValuationEngine quality/complexity scoring on a company.
        Returns quality_score (0-1), complexity, suggested WACC, confidence.
        """
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.sector, cf.revenue, cf.ebitda, cf.market_cap_estimate,
                       cf.debt, cf.cash, cf.beta, cf.growth_rate_y1, cf.terminal_growth,
                       cf.profit_margin, cf.capex_pct
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                WHERE c.id = {ph}
            """, (company_id,))
            row = cur.fetchone()
            conn.close()

            if not row:
                return jsonify({'error': 'Company not found'}), 404

            company_data = _row_to_dict(row)
            score = compute_institutional_score(company_data)
            score['company_id'] = company_id
            return jsonify(score)

        except Exception as e:
            logger.error(f'Institutional score endpoint failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

        # ── Portfolio Optimization ─────────────────────────────────────────────────

    @app.route('/api/portfolio/optimize', methods=['POST'])
    def optimize_portfolio():
        """
        Build optimal portfolio from all companies with valuations.
        Uses mean-variance optimization (Markowitz) + valuation conviction weighting.
        """
        try:
            from portfolio_engine import PortfolioEngine, PortfolioConstraints

            body = request.get_json(force=True) or {}
            constraints_raw = body.get('constraints', {})
            target_value = float(body.get('target_value', 1_000_000))

            constraints = PortfolioConstraints(
                max_single_position=constraints_raw.get('max_single_position', 0.20),
                min_single_position=constraints_raw.get('min_single_position', 0.02),
                max_sector_exposure=constraints_raw.get('max_sector_exposure', 0.40),
                risk_tolerance=constraints_raw.get('risk_tolerance', 'Moderate'),
                target_num_holdings=constraints_raw.get('target_num_holdings', 15),
            )

            # Fetch all companies with their latest valuations
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute("""
                SELECT c.id, c.name, c.ticker, c.sector,
                       vr.final_price_per_share, vr.current_price,
                       vr.upside_pct, vr.recommendation, vr.wacc,
                       cf.revenue, cf.ebitda, cf.market_cap_estimate,
                       cf.beta, cf.terminal_growth, cf.growth_rate_y1
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                    AND vr.id = (
                        SELECT MAX(id) FROM valuation_results WHERE company_id = c.id
                    )
                ORDER BY c.name
            """)
            rows = [_row_to_dict(r) for r in cur.fetchall()]
            # Phase 0d: map upside_pct -> upside for PortfolioEngine; guard null ticker
            for r in rows:
                r['upside'] = r.get('upside_pct') or 0
                if not r.get('ticker'):
                    r['ticker'] = r.get('name', 'UNKNOWN')[:10]
            conn.close()

            if not rows:
                return jsonify({'error': 'No companies with valuations found'}), 404

            engine = PortfolioEngine()
            allocations, metrics = engine.build_portfolio(rows, constraints, target_value)

            report = engine.generate_portfolio_report(
                allocations, metrics, rows, target_value
            )

            # Compute weighted upside from allocations + company data
            ticker_upside = {r.get('ticker', ''): r.get('upside_pct', 0) or 0 for r in rows}
            weighted_upside = sum(
                allocations.get(t, 0) * ticker_upside.get(t, 0)
                for t in allocations
            )

            return jsonify({
                'allocations': allocations,
                'metrics': {
                    'expected_return': metrics.expected_return,
                    'volatility': metrics.volatility,
                    'sharpe_ratio': metrics.sharpe_ratio,
                    'sortino_ratio': getattr(metrics, 'sortino_ratio', None),
                    'max_drawdown': getattr(metrics, 'max_drawdown', None),
                    'num_holdings': metrics.num_holdings,
                    'sector_breakdown': getattr(metrics, 'sector_concentration', {}),
                    'largest_position': getattr(metrics, 'largest_position', None),
                    'weighted_upside': round(weighted_upside, 2),
                    'total_conviction': getattr(metrics, 'total_conviction_score', None),
                },
                'report': report,
                'generated_at': datetime.utcnow().isoformat(),
            })

        except Exception as e:
            logger.error(f'Portfolio optimization failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── Shareable Read-Only Links ──────────────────────────────────────────────

    @app.route('/api/company/<int:company_id>/share', methods=['POST'])
    def create_share_link(company_id):
        """Create a shareable read-only link for a company valuation snapshot."""
        try:
            import secrets
            from datetime import timedelta

            # Fetch latest valuation snapshot
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.name, c.ticker, c.sector,
                       vr.final_price_per_share, vr.current_price, vr.upside_pct,
                       vr.recommendation, vr.wacc, vr.created_at
                FROM companies c
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                    AND vr.id = (SELECT MAX(id) FROM valuation_results WHERE company_id = {ph})
                WHERE c.id = {ph}
            """, (company_id, company_id))
            row = cur.fetchone()

            if not row:
                conn.close()
                return jsonify({'error': 'Company not found'}), 404

            snapshot = _row_to_dict(row)
            token = secrets.token_urlsafe(24)
            expires_at = (datetime.utcnow() + timedelta(days=30)).isoformat()

            # Ensure share_links table exists
            cur.execute("""
                CREATE TABLE IF NOT EXISTS share_links (
                    token TEXT PRIMARY KEY,
                    company_id INTEGER,
                    valuation_snapshot TEXT,
                    created_at TEXT,
                    expires_at TEXT,
                    view_count INTEGER DEFAULT 0
                )
            """)
            cur.execute(
                f"INSERT INTO share_links (token, company_id, valuation_snapshot, created_at, expires_at) VALUES ({ph},{ph},{ph},{ph},{ph})",
                (token, company_id, json.dumps(snapshot), datetime.utcnow().isoformat(), expires_at)
            )
            conn.commit()
            conn.close()

            return jsonify({
                'token': token,
                'share_url': f'/share/{token}',
                'expires_at': expires_at,
            })

        except Exception as e:
            logger.error(f'Share link creation failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    @app.route('/share/<token>', methods=['GET'])
    def view_share_link(token):
        """Render a read-only valuation view for a shared link."""
        from flask import render_template_string
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT * FROM share_links WHERE token = {ph}", (token,))
            row = cur.fetchone()
            conn.close()

            if not row:
                return render_template_string(SHARE_NOT_FOUND_HTML, reason='Link not found'), 404

            link = _row_to_dict(row)
            if link['expires_at'] and link['expires_at'] < datetime.utcnow().isoformat():
                return render_template_string(SHARE_NOT_FOUND_HTML, reason='This link has expired'), 410

            # Increment view count
            try:
                conn2, ph2 = _get_db()
                cur2 = conn2.cursor()
                cur2.execute(f"UPDATE share_links SET view_count = view_count + 1 WHERE token = {ph2}", (token,))
                conn2.commit()
                conn2.close()
            except Exception:
                pass

            snapshot = json.loads(link['valuation_snapshot'])
            created_at = link['created_at'][:10] if link['created_at'] else 'Unknown'

            return render_template_string(
                SHARE_VIEW_HTML,
                snapshot=snapshot,
                created_at=created_at,
                view_count=link.get('view_count', 0) + 1,
            )

        except Exception as e:
            logger.error(f'Share link view failed for token {token}: {e}', exc_info=True)
            return render_template_string(SHARE_NOT_FOUND_HTML, reason='An error occurred'), 500


    # ── Phase 0a: Assumption Suggestions ──────────────────────────────────────

    @app.route('/api/company/<int:company_id>/assumption-suggestions', methods=['GET'])
    def get_assumption_suggestions(company_id):
        """Return AI-suggested WACC and terminal growth with rationale."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT c.*, cf.* FROM companies c JOIN company_financials cf ON c.id = cf.company_id WHERE c.id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            inst = compute_institutional_score(row)
            return jsonify({
                'company_id': company_id,
                'suggested_wacc': inst.get('suggested_wacc'),
                'suggested_terminal_growth': inst.get('suggested_terminal_growth'),
                'assumption_rationale': inst.get('wacc_rationale', ''),
                'quality_score': inst.get('quality_score'),
                'complexity': inst.get('complexity'),
                'confidence': inst.get('confidence'),
                'generated_at': datetime.utcnow().isoformat(),
            })
        except Exception as e:
            logger.error(f'Assumption suggestions failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── Phase 0b: Smart Money (full 13F) ──────────────────────────────────────

    @app.route('/api/company/<int:company_id>/smart-money', methods=['GET'])
    def get_smart_money(company_id):
        """Institutional 13F holdings for this company (full XML parse)."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT ticker, name, sector FROM companies WHERE id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            ticker = row.get('ticker') or row.get('name', '')
            from intelligence.smart_money import get_smart_money_positions
            result = get_smart_money_positions(ticker, limit_filers=8)

            # Add AI summary if LLM key available
            try:
                from services.llm import summarize_smart_money
                holders = [p for p in result.get('positions', []) if p.get('shares', 0) > 0]
                result['summary'] = summarize_smart_money(holders, row)
            except Exception as llm_err:
                logger.debug(f'Smart money LLM summary skipped: {llm_err}')

            return jsonify(result)
        except Exception as e:
            logger.error(f'Smart money endpoint failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    # ── Phase 0c: Alert Trigger Endpoints ─────────────────────────────────────

    @app.route('/api/alerts/check', methods=['POST'])
    def check_alerts():
        """Trigger alert checks for a ticker (earnings revision, insider cluster)."""
        try:
            body = request.get_json(force=True) or {}
            ticker = body.get('ticker', '')
            company_id = body.get('company_id')
            if not ticker:
                return jsonify({'error': 'ticker required'}), 400

            from intelligence.alert_engine import check_earnings_revision_alert, check_insider_cluster_alert, check_macro_move_alert
            check_earnings_revision_alert(ticker, company_id)
            check_insider_cluster_alert(ticker, company_id)
            check_macro_move_alert(company_id)

            return jsonify({'status': 'checks_triggered', 'ticker': ticker})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    # ── Phase 1: LLM Commentary & Thesis ──────────────────────────────────────

    @app.route('/api/company/<int:company_id>/commentary', methods=['GET'])
    def get_valuation_commentary(company_id):
        """Generate AI commentary on the latest DCF valuation."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.id, c.name, c.ticker, c.sector,
                       cf.revenue, cf.ebitda, cf.market_cap_estimate, cf.beta,
                       vr.final_price_per_share, vr.current_price, vr.upside_pct,
                       vr.recommendation, vr.wacc
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                    AND vr.id = (SELECT MAX(id) FROM valuation_results WHERE company_id = c.id)
                WHERE c.id = {ph}
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            from services.llm import generate_valuation_commentary

            # Try RAG context
            rag_context = None
            try:
                from services.rag import retrieve_context
                chunks = retrieve_context(row.get('ticker', ''), 'revenue growth outlook', top_k=3)
                if chunks:
                    rag_context = '\n'.join(c['content'][:400] for c in chunks)
            except Exception:
                pass

            commentary = generate_valuation_commentary(row, row, rag_context=rag_context)
            return jsonify({'company_id': company_id, 'commentary': commentary, 'generated_at': datetime.utcnow().isoformat()})
        except Exception as e:
            logger.error(f'Commentary endpoint failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    @app.route('/api/company/<int:company_id>/thesis', methods=['POST'])
    def generate_thesis(company_id):
        """Generate bull/bear investment thesis using LLM."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"""
                SELECT c.id, c.name, c.ticker, c.sector,
                       cf.revenue, cf.ebitda, cf.market_cap_estimate,
                       vr.final_price_per_share, vr.current_price, vr.upside_pct,
                       vr.recommendation, vr.wacc
                FROM companies c
                JOIN company_financials cf ON c.id = cf.company_id
                LEFT JOIN valuation_results vr ON c.id = vr.company_id
                    AND vr.id = (SELECT MAX(id) FROM valuation_results WHERE company_id = c.id)
                WHERE c.id = {ph}
            """, (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            from services.llm import generate_investment_thesis

            rag_context = None
            try:
                from services.rag import retrieve_context
                chunks = retrieve_context(row.get('ticker', ''), 'competitive position growth strategy', top_k=3)
                if chunks:
                    rag_context = '\n'.join(c['content'][:300] for c in chunks)
            except Exception:
                pass

            thesis = generate_investment_thesis(row, row, rag_context=rag_context)
            return jsonify({'company_id': company_id, **thesis, 'generated_at': datetime.utcnow().isoformat()})
        except Exception as e:
            logger.error(f'Thesis endpoint failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    @app.route('/api/company/<int:company_id>/anomalies/explain', methods=['GET'])
    def explain_anomalies(company_id):
        """Get anomalies with AI explanation for each."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT c.*, cf.* FROM companies c JOIN company_financials cf ON c.id = cf.company_id WHERE c.id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            from intelligence.anomaly_detector import analyze_assumptions
            anomalies = analyze_assumptions(row, row.get('sector', ''))

            try:
                from services.llm import explain_anomaly
                for a in anomalies:
                    a['explanation'] = explain_anomaly(a, row)
            except Exception as llm_err:
                logger.debug(f'Anomaly explanation skipped: {llm_err}')

            return jsonify({'company_id': company_id, 'anomalies': anomalies, 'generated_at': datetime.utcnow().isoformat()})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    # ── Phase 2: RAG Document Intelligence ────────────────────────────────────

    @app.route('/api/company/<int:company_id>/ingest-docs', methods=['POST'])
    def ingest_docs(company_id):
        """Trigger 10-K ingestion into pgvector for RAG."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT ticker, name FROM companies WHERE id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            ticker = row.get('ticker') or row.get('name', '')
            from services.rag import ingest_10k
            chunk_count = ingest_10k(ticker, company_id)
            return jsonify({'company_id': company_id, 'ticker': ticker, 'chunks_stored': chunk_count, 'status': 'complete'})
        except Exception as e:
            logger.error(f'Doc ingest failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    @app.route('/api/company/<int:company_id>/ask', methods=['POST'])
    def ask_filing(company_id):
        """Ask a question grounded in the company's 10-K (RAG)."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT ticker, name FROM companies WHERE id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            body = request.get_json(force=True) or {}
            question = body.get('question', '')
            if not question:
                return jsonify({'error': 'question required'}), 400

            ticker = row.get('ticker') or row.get('name', '')
            from services.rag import answer_question
            result = answer_question(ticker, question)
            return jsonify({'company_id': company_id, 'ticker': ticker, **result})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    @app.route('/api/company/<int:company_id>/docs', methods=['GET'])
    def list_docs(company_id):
        """List ingested documents for a company."""
        try:
            conn, ph = _get_db()
            cur = conn.cursor()
            cur.execute(f"SELECT ticker, name FROM companies WHERE id = {ph}", (company_id,))
            row = _row_to_dict(cur.fetchone())
            conn.close()
            if not row:
                return jsonify({'error': 'Company not found'}), 404

            ticker = row.get('ticker') or row.get('name', '')
            from services.rag import list_ingested_docs
            docs = list_ingested_docs(ticker)
            return jsonify({'company_id': company_id, 'ticker': ticker, 'documents': docs})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    # ── Phase 4: AI Analyst Agent ──────────────────────────────────────────────

    @app.route('/api/agent/analyze', methods=['POST'])
    def agent_analyze():
        """
        AI Analyst Agent: natural language → full investment memo.
        Body: {"query": "Analyze MSFT as a buyout target", "company_id": 1}
        """
        try:
            body = request.get_json(force=True) or {}
            query = body.get('query', '')
            company_id_hint = body.get('company_id')

            if not query:
                return jsonify({'error': 'query required'}), 400

            from services.agent import analyze
            result = analyze(query, company_id=company_id_hint)
            return jsonify(result)
        except Exception as e:
            logger.error(f'Agent analyze failed: {e}', exc_info=True)
            return jsonify({'error': str(e)}), 500

    @app.route('/api/agent/analyze/stream', methods=['POST'])
    def agent_analyze_stream():
        """SSE stream of agent steps. Body: same as /api/agent/analyze."""
        import queue, threading

        body = request.get_json(force=True) or {}
        query = body.get('query', '')
        company_id_hint = body.get('company_id')

        if not query:
            return jsonify({'error': 'query required'}), 400

        def generate():
            import json as _json
            try:
                # Run agent in blocking mode, stream step events
                from services.agent import analyze, TOOLS, _api_key, _SYSTEM_PROMPT, _execute_tool, _MAX_ITERATIONS, _BASE_URL, _MODEL
                import httpx as _httpx

                messages = [
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": f"Query: {query}" + (f"\nCompany ID: {company_id_hint}" if company_id_hint else "")},
                ]
                headers = {
                    "Authorization": f"Bearer {_api_key()}",
                    "Content-Type": "application/json",
                    "HTTP-Referer": "https://axiom.local",
                }

                for iteration in range(_MAX_ITERATIONS):
                    payload = {"model": _MODEL, "messages": messages, "tools": TOOLS, "max_tokens": 2000}
                    resp = _httpx.post(f"{_BASE_URL}/chat/completions", headers=headers, json=payload, timeout=90)
                    resp.raise_for_status()
                    data = resp.json()
                    choice = data["choices"][0]
                    message = choice["message"]
                    messages.append(message)

                    tool_calls = message.get("tool_calls", [])
                    if tool_calls:
                        for tc in tool_calls:
                            fn_name = tc["function"]["name"]
                            fn_params = _json.loads(tc["function"]["arguments"])
                            yield f"data: {_json.dumps({'type': 'step', 'tool': fn_name, 'params': fn_params})}\n\n"
                            result = _execute_tool(fn_name, fn_params, company_id_hint)
                            messages.append({"role": "tool", "tool_call_id": tc["id"], "content": _json.dumps(result)[:4000]})
                    elif choice.get("finish_reason") in ("stop", "end_turn"):
                        yield f"data: {_json.dumps({'type': 'complete', 'memo': message.get('content', '')})}\n\n"
                        return

                yield f"data: {_json.dumps({'type': 'error', 'message': 'Max iterations reached'})}\n\n"
            except Exception as e:
                yield f"data: {_json.dumps({'type': 'error', 'message': str(e)})}\n\n"

        return Response(generate(), mimetype='text/event-stream',
                        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'})

    logger.info("AXIOM routes registered: macro, lbo, football-field, sensitivity, export, stream, alerts, portfolio, share + AI: assumption-suggestions, smart-money, commentary, thesis, anomalies/explain, ingest-docs, ask, docs, agent/analyze")
